version: "3.9"
services:
  web:
    image: "localhost/web:latest"
    build: .
    ports:
      - 8000:5000
    volumes:
      - ${HOME}/data:/data
      - ${HOME}/data/worker:/mbg/instance/shared
    environment:
      FLASK_APP: "mbg.csi:create_app"
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      MARIADB_PASSWORD: ${MARIADB_CREDENTIAL}
    depends_on:
      rabbitmq:
        condition: service_started
  rabbitmq:
    image: rabbitmq:3-management-alpine
    command: ash -c "echo 'log.console.level = warning'
      >>/etc/rabbitmq/conf.d/10-default-guest-user.conf && rabbitmq-server"
    ports:
      - 5672:5672
      - 15672:15672
  worker:
    image: "localhost/web:latest"
    depends_on:
      - rabbitmq
      - web
    command: celery -A mbg.csi.make_celery.celery_app worker --loglevel INFO --concurrency=4
    volumes:
      - ${HOME}/data:/data
      - ${HOME}/data/worker:/mbg/instance/shared
    environment:
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
      MARIADB_PASSWORD: ${MARIADB_CREDENTIAL}
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_CREDENTIAL}
      MARIADB_PASSWORD: ${MARIADB_CREDENTIAL}
      MARIADB_USER: mbg
      MARIADB_DATABASE: csi
